name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'project/NikGapps/helper/assets/changelogs.yaml'
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Fetch the latest release version
        id: latest_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .name)
          echo "LATEST_VERSION=$LATEST_VERSION"
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Increment the version
        id: increment_version
        run: |
          PARTS=(${LATEST_VERSION//./ })
          V_MAJOR=${PARTS[0]}
          V_MINOR=$((${PARTS[1]} + 1))
          NEW_VERSION="$V_MAJOR.$V_MINOR"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.new_version }}
          release_name: Release ${{ steps.increment_version.outputs.new_version }}
          draft: false
          prerelease: false
