name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check for keyword in commit messages
        id: keyword-check
        run: |
          commit_message=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | \
            jq -r '.commit.message')

          if echo "$commit_message" | grep -iq 'Release:'; then
            echo "::set-output name=keyword_found::true"
          else
            echo "::set-output name=keyword_found::false"
          fi

      - name: Create Release
        if: steps.keyword-check.outputs.keyword_found == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
