name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check for keyword in commit messages
        id: keyword-check
        run: |
          commit_message=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | \
            jq -r '.commit.message')

          if echo "$commit_message" | grep -iq 'Release:'; then
            echo "KEYWORD_FOUND=true" >> $GITHUB_ENV
          else
            echo "KEYWORD_FOUND=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        if: env.KEYWORD_FOUND == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: "v1.$(date +'%Y%m%d%H%M%S')"
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
